# flutter analyze : 静的解析を実行
# dart fix --dry-run : Dart標準機能で自動修正可能な issue を表示
# dart fix --apply : 実際に自動修正する

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/types/**.g.dart
    - lib/types/**.freezed.dart
    - lib/poker_plus/**.g.dart
    - lib/poker_plus/**.freezed.dart

linter:
  rules:
    use_key_in_widget_constructors: false # Key を使いこなせないため
